import { mockIp, mockReqId } from '../../utils/mock';

export function genOrders(params) {
  const resp = {
    data: {
      pageNum: 1,
      pageSize: 10,
      totalCount: 7,
      orders: [
        {
          saasId: '88888888',
          storeId: '1000',
          storeName: 'NAGASHIRO水产东京旗舰店',
          uid: '88888888205468',
          parentOrderNo: '354021731671873099',
          orderId: '354021735982432279',
          orderNo: '354021731671873099',
          orderType: 0,
          orderSubType: 0,
          orderStatus: 5,
          orderSubStatus: null,
          totalAmount: '10010',
          goodsAmount: '10000',
          goodsAmountApp: '10000',
          paymentAmount: '20',
          freightFee: '10',
          packageFee: '0',
          discountAmount: '9990',
          channelType: 0,
          channelSource: '',
          channelIdentity: '',
          remark: '',
          cancelType: null,
          cancelReasonType: null,
          cancelReason: null,
          rightsType: null,
          createTime: '1600350829291',
          orderItemVOs: [
            {
              id: '354021736133427225',
              orderNo: null,
              spuId: '3',
              skuId: '135696670',
              roomId: null,
              goodsMainType: 0,
              goodsViceType: 0,
              goodsName:
                'ぶり',
              title: '鲷鱼',
              title_en: 'Buri',
              title_jp: 'ぶり',
              specifications: [
              ],
              goodsPictureUrl:
                'cloud://nagashiro-7gx3ygvt2a49505e.6e61-nagashiro-7gx3ygvt2a49505e-1327079852/images/goods_demo_rename/A/A1/03.jpg',
              originPrice: '28000',
              actualPrice: '28000',
              buyQuantity: 1,
              itemTotalAmount: '28000',
              itemDiscountAmount: '28000',
              itemPaymentAmount: '10',
              goodsPaymentPrice: '10',
              tagPrice: null,
              tagText: null,
              outCode: null,
              labelVOs: null,
              buttonVOs: null,
            },
          ],
          logisticsVO: {
            logisticsType: 1,
            logisticsNo: '',
            logisticsStatus: null,
            logisticsCompanyCode: '',
            logisticsCompanyName: '',
            receiverAddressId: '14',
            provinceCode: '440000',
            cityCode: '440300',
            countryCode: '440306',
            receiverProvince: '广东省',
            receiverCity: '深圳市',
            receiverCountry: '宝安区',
            receiverArea: '',
            receiverAddress: '沙井中心路28号丽沙花都xx栋xx号',
            receiverPostCode: '',
            receiverLongitude: '113.829127',
            receiverLatitude: '22.713649',
            receiverIdentity: '88888888205468',
            receiverPhone: '17612345678',
            receiverName: '测试用户',
            expectArrivalTime: null,
            senderName: '',
            senderPhone: '',
            senderAddress: '',
            sendTime: null,
            arrivalTime: null,
          },
          paymentVO: {
            payStatus: 1,
            amount: '20',
            currency: null,
            payType: null,
            payWay: null,
            payWayName: null,
            interactId: null,
            traceNo: null,
            channelTrxNo: null,
            period: null,
            payTime: null,
            paySuccessTime: null,
          },
          buttonVOs: [
            { primary: false, type: 2, name: '取消订单' },
            { primary: true, type: 1, name: '付款' },
          ],
          labelVOs: null,
          invoiceVO: null,
          couponAmount: null,
          autoCancelTime: '1600352629291',
          orderStatusName: '待付款',
          orderSatusRemark: '需支付￥0.20',
          logisticsLogVO: null,
          invoiceStatus: null,
          invoiceDesc: null,
          invoiceUrl: null,
        },
        {
          saasId: '88888888',
          storeId: '1000',
          storeName: 'NAGASHIRO水产东京旗舰店',
          uid: '88888888205468',
          parentOrderNo: '132381532610540875',
          orderId: '132381537256650240',
          orderNo: '132381532610540875',
          orderType: 0,
          orderSubType: 0,
          orderStatus: 10,
          orderSubStatus: null,
          totalAmount: '76600',
          goodsAmount: '76600',
          goodsAmountApp: '76600',
          paymentAmount: '36800',
          freightFee: '0',
          packageFee: '0',
          discountAmount: '39800',
          channelType: 0,
          channelSource: '',
          channelIdentity: '',
          remark: '',
          cancelType: null,
          cancelReasonType: null,
          cancelReason: null,
          rightsType: null,
          createTime: '1587140043980',
          orderItemVOs: [
            {
              id: '132381537407645696',
              orderNo: null,
              spuId: '0',
              skuId: '135676631',
              roomId: null,
              goodsMainType: 0,
              goodsViceType: 0,
              goodsName: '养殖鲭鱼',
              title: '养殖鲭鱼',
              title_en: 'Farming Mackerel',
              title_jp: '養殖サバ',
              goodsPictureUrl: 'cloud://nagashiro-7gx3ygvt2a49505e.6e61-nagashiro-7gx3ygvt2a49505e-1327079852/images/goods_demo_rename/A/A1/01.jpg',
              originPrice: '20000',
              actualPrice: '20000',
              specifications: [
              ],
              buyQuantity: 1,
              itemTotalAmount: '20000',
              itemDiscountAmount: '0',
              itemPaymentAmount: '20000',
              goodsPaymentPrice: '20000',
              tagPrice: null,
              tagText: null,
              outCode: null,
              labelVOs: null,
              buttonVOs: null,
            },
            {
              id: '132381537407645952',
              orderNo: null,
              spuId: '7',
              skuId: '135691633',
              roomId: null,
              goodsMainType: 0,
              goodsViceType: 0,
              goodsName:'本マグロ',
              title: '蓝鳍金枪鱼',
              title_en: 'Bluefin Tuna',
              title_jp: '本マグロ',
              goodsPictureUrl: 'cloud://nagashiro-7gx3ygvt2a49505e.6e61-nagashiro-7gx3ygvt2a49505e-1327079852/images/goods_demo_rename/A/A3/01.jpg',
              originPrice: '45000',
              actualPrice: '45000',
              specifications: [
              ],
              buyQuantity: 1,
              itemTotalAmount: '45000',
              itemDiscountAmount: '0',
              itemPaymentAmount: '45000',
              goodsPaymentPrice: '45000',
              tagPrice: null,
              tagText: null,
              outCode: null,
              labelVOs: null,
              buttonVOs: null,
            },
            {
              id: '132381537407646208',
              orderNo: null,
              spuId: '5',
              skuId: '135691631',
              roomId: null,
              goodsMainType: 0,
              goodsViceType: 0,
              goodsName: 'カンパチ',
              title: '宽额大眼鲷',
              title_en: 'Kanpachi',
              title_jp: 'カンパチ',
              goodsPictureUrl: 'cloud://nagashiro-7gx3ygvt2a49505e.6e61-nagashiro-7gx3ygvt2a49505e-1327079852/images/goods_demo_rename/A/A1/05.jpg',
              originPrice: '27000',
              actualPrice: '27000',
              specifications: [
              ],
              buyQuantity: 1,
              itemTotalAmount: '27000',
              itemDiscountAmount: '0',
              itemPaymentAmount: '27000',
              goodsPaymentPrice: '27000',
              tagPrice: null,
              tagText: null,
              outCode: null,
              labelVOs: null,
              buttonVOs: null,
            },
          ],
          logisticsVO: {
            logisticsType: 1,
            logisticsNo: '',
            logisticsStatus: null,
            logisticsCompanyCode: '',
            logisticsCompanyName: '',
            receiverAddressId: '2',
            provinceCode: '440000',
            cityCode: '440300',
            countryCode: '440306',
            receiverProvince: '广东省',
            receiverCity: '深圳市',
            receiverCountry: '南山区',
            receiverArea: '',
            receiverAddress: '前海路333号阳光玫瑰园',
            receiverPostCode: '',
            receiverLongitude: '113.829127',
            receiverLatitude: '22.713649',
            receiverIdentity: '88888888205468',
            receiverPhone: '17612345678',
            receiverName: '平均线',
            expectArrivalTime: null,
            senderName: '',
            senderPhone: '',
            senderAddress: '',
            sendTime: null,
            arrivalTime: null,
          },
          paymentVO: {
            payStatus: 1,
            amount: '36800',
            currency: null,
            payType: null,
            payWay: null,
            payWayName: null,
            interactId: null,
            traceNo: null,
            channelTrxNo: null,
            period: null,
            payTime: null,
            paySuccessTime: null,
          },
          buttonVOs: [
            {
              primary: false,
              type: 2,
              name: '取消订单',
            },
            {
              primary: true,
              type: 9,
              name: '再次购买',
            },
          ],
          labelVOs: null,
          invoiceVO: null,
          couponAmount: null,
          autoCancelTime: null,
          orderStatusName: '待发货',
          orderSatusRemark: null,
          logisticsLogVO: null,
          invoiceStatus: null,
          invoiceDesc: null,
          invoiceUrl: null,
        },
        {
          saasId: '88888888',
          storeId: '1000',
          storeName: 'NAGASHIRO水产东京旗舰店',
          uid: '88888888205468',
          parentOrderNo: '132222623132329291',
          orderId: '132222629674264064',
          orderNo: '132222623132329291',
          orderType: 0,
          orderSubType: 0,
          orderStatus: 40,
          orderSubStatus: null,
          totalAmount: '27000',
          goodsAmount: '27000',
          goodsAmountApp: '27000',
          paymentAmount: '27000',
          freightFee: '0',
          packageFee: '0',
          discountAmount: '0',
          channelType: 0,
          channelSource: '',
          channelIdentity: '',
          remark: '',
          cancelType: null,
          cancelReasonType: null,
          cancelReason: null,
          rightsType: null,
          createTime: '1587130572349',
          orderItemVOs: [
            {
              id: '132222629825259776',
              orderNo: null,
              spuId: '5',
              skuId: '135691625',
              roomId: null,
              goodsMainType: 0,
              goodsViceType: 0,
              goodsName:
                'カンパチ',
              title: '宽额大眼鲷',
              title_en: 'Kanpachi',
              title_jp: 'カンパチ',
              goodsPictureUrl: 'cloud://nagashiro-7gx3ygvt2a49505e.6e61-nagashiro-7gx3ygvt2a49505e-1327079852/images/goods_demo_rename/A/A1/05.jpg',
              originPrice: '27000',
              actualPrice: '27000',
              specifications: [
              ],
              buyQuantity: 1,
              itemTotalAmount: '27000',
              itemDiscountAmount: '0',
              itemPaymentAmount: '27000',
              goodsPaymentPrice: '27000',
              tagPrice: null,
              tagText: null,
              outCode: null,
              labelVOs: null,
              buttonVOs: null,
            },
            
          ],
          logisticsVO: {
            logisticsType: 1,
            logisticsNo: '',
            logisticsStatus: null,
            logisticsCompanyCode: '',
            logisticsCompanyName: '',
            receiverAddressId: '2',
            provinceCode: '440000',
            cityCode: '440300',
            countryCode: '440306',
            receiverProvince: '广东省',
            receiverCity: '深圳市',
            receiverCountry: '南山区',
            receiverArea: '',
            receiverAddress: '前海路333号阳光玫瑰园',
            receiverPostCode: '',
            receiverLongitude: '113.829127',
            receiverLatitude: '22.713649',
            receiverIdentity: '88888888205468',
            receiverPhone: '17612345678',
            receiverName: '平均线',
            expectArrivalTime: null,
            senderName: '',
            senderPhone: '',
            senderAddress: '',
            sendTime: null,
            arrivalTime: null,
          },
          paymentVO: {
            payStatus: 1,
            amount: '458600',
            currency: null,
            payType: null,
            payWay: null,
            payWayName: null,
            interactId: null,
            traceNo: null,
            channelTrxNo: null,
            period: null,
            payTime: null,
            paySuccessTime: null,
          },
          buttonVOs: [
            {
              primary: true,
              type: 3,
              name: '确认收货',
            },
          ],
          labelVOs: null,
          invoiceVO: null,
          couponAmount: null,
          autoCancelTime: null,
          orderStatusName: '待收货',
          orderSatusRemark: null,
          logisticsLogVO: null,
          invoiceStatus: null,
          invoiceDesc: null,
          invoiceUrl: null,
        },
        {
          saasId: '88888888',
          storeId: '1000',
          storeName: 'NAGASHIRO水产东京旗舰店',
          uid: '88888888205468',
          parentOrderNo: '130862219672031307',
          orderId: '130862224737571072',
          orderNo: '130862219672031307',
          orderType: 0,
          orderSubType: 0,
          orderStatus: 80,
          orderSubStatus: null,
          totalAmount: '500000',
          goodsAmount: '500000',
          goodsAmountApp: '500000',
          paymentAmount: '500000',
          freightFee: '0',
          packageFee: '0',
          discountAmount: '0',
          channelType: 0,
          channelSource: '',
          channelIdentity: '',
          remark: '',
          cancelType: null,
          cancelReasonType: null,
          cancelReason: null,
          rightsType: null,
          createTime: '1587049485899',
          orderItemVOs: [
            {
              id: '130862224922120960',
              orderNo: null,
              spuId: '14',
              skuId: '135676631',
              roomId: null,
              goodsMainType: 0,
              goodsViceType: 0,
              goodsName:
                'ウニ',
              goodsPictureUrl: 'cloud://nagashiro-7gx3ygvt2a49505e.6e61-nagashiro-7gx3ygvt2a49505e-1327079852/images/goods_demo_rename/A/A7/01.jpg',
              originPrice: '40000',
              actualPrice: '29800',
              specifications: [
              ],
              buyQuantity: 10,
              itemTotalAmount: '50000',
              itemDiscountAmount: '0',
              itemPaymentAmount: '500000',
              goodsPaymentPrice: '50000',
              tagPrice: null,
              tagText: null,
              outCode: null,
              labelVOs: null,
              buttonVOs: null,
            },
          ],
          logisticsVO: {
            logisticsType: 1,
            logisticsNo: '',
            logisticsStatus: null,
            logisticsCompanyCode: '',
            logisticsCompanyName: '',
            receiverAddressId: '2',
            provinceCode: '440000',
            cityCode: '440300',
            countryCode: '440306',
            receiverProvince: '广东省',
            receiverCity: '深圳市',
            receiverCountry: '南山区',
            receiverArea: '',
            receiverAddress: '前海路333号阳光玫瑰园',
            receiverPostCode: '',
            receiverLongitude: '113.829127',
            receiverLatitude: '22.713649',
            receiverIdentity: '88888888205468',
            receiverPhone: '17612345678',
            receiverName: '平均线',
            expectArrivalTime: null,
            senderName: '',
            senderPhone: '',
            senderAddress: '',
            sendTime: null,
            arrivalTime: null,
          },
          paymentVO: {
            payStatus: 1,
            amount: '263200',
            currency: null,
            payType: null,
            payWay: null,
            payWayName: null,
            interactId: null,
            traceNo: null,
            channelTrxNo: null,
            period: null,
            payTime: null,
            paySuccessTime: null,
          },
          buttonVOs: null,
          labelVOs: null,
          invoiceVO: null,
          couponAmount: null,
          autoCancelTime: null,
          orderStatusName: '已取消',
          orderSatusRemark: null,
          logisticsLogVO: null,
          invoiceStatus: null,
          invoiceDesc: null,
          invoiceUrl: null,
        },
        {
          saasId: '88888888',
          storeId: '1000',
          storeName: 'NAGASHIRO水产东京旗舰店',
          uid: '88888888205468',
          parentOrderNo: '130494472895208267',
          orderId: '130494482155052032',
          orderNo: '130494472895208267',
          orderType: 0,
          orderSubType: 0,
          orderStatus: 80,
          orderSubStatus: null,
          totalAmount: '135000',
          goodsAmount: '135000',
          goodsAmountApp: '135000',
          paymentAmount: '135000',
          freightFee: '0',
          packageFee: '0',
          discountAmount: '0',
          channelType: 0,
          channelSource: '',
          channelIdentity: '',
          remark: '',
          cancelType: null,
          cancelReasonType: null,
          cancelReason: null,
          rightsType: null,
          createTime: '1587027566730',
          orderItemVOs: [
            {
              id: '130494482322824704',
              orderNo: null,
              spuId: '7',
              skuId: '135691633',
              roomId: null,
              goodsMainType: 0,
              goodsViceType: 0,
              goodsName:
                '本マグロ',
              goodsPictureUrl: 'cloud://nagashiro-7gx3ygvt2a49505e.6e61-nagashiro-7gx3ygvt2a49505e-1327079852/images/goods_demo_rename/A/A3/01.jpg',
              originPrice: '45000',
              actualPrice: '45000',
              specifications: [
                { specTitle: '颜色', specValue: '奶黄色' },
                { specTitle: '类型', specValue: '三件套' },
              ],
              buyQuantity: 3,
              itemTotalAmount: '135000',
              itemDiscountAmount: '0',
              itemPaymentAmount: '135000',
              goodsPaymentPrice: '45000',
              tagPrice: null,
              tagText: null,
              outCode: null,
              labelVOs: null,
              buttonVOs: null,
            },
          ],
          logisticsVO: {
            logisticsType: 1,
            logisticsNo: '',
            logisticsStatus: null,
            logisticsCompanyCode: '',
            logisticsCompanyName: '',
            receiverAddressId: '2',
            provinceCode: '440000',
            cityCode: '440300',
            countryCode: '440306',
            receiverProvince: '广东省',
            receiverCity: '深圳市',
            receiverCountry: '南山区',
            receiverArea: '',
            receiverAddress: '前海路333号阳光玫瑰园',
            receiverPostCode: '',
            receiverLongitude: '113.829127',
            receiverLatitude: '22.713649',
            receiverIdentity: '88888888205468',
            receiverPhone: '17612345678',
            receiverName: '平均线',
            expectArrivalTime: null,
            senderName: '',
            senderPhone: '',
            senderAddress: '',
            sendTime: null,
            arrivalTime: null,
          },
          paymentVO: {
            payStatus: 1,
            amount: '24900',
            currency: null,
            payType: null,
            payWay: null,
            payWayName: null,
            interactId: null,
            traceNo: null,
            channelTrxNo: null,
            period: null,
            payTime: null,
            paySuccessTime: null,
          },
          buttonVOs: null,
          labelVOs: null,
          invoiceVO: null,
          couponAmount: null,
          autoCancelTime: null,
          orderStatusName: '已取消',
          orderSatusRemark: null,
          logisticsLogVO: null,
          invoiceStatus: null,
          invoiceDesc: null,
          invoiceUrl: null,
        },
        {
          saasId: '88888888',
          storeId: '1000',
          storeName: 'NAGASHIRO水产东京旗舰店',
          uid: '88888888205468',
          parentOrderNo: '130169571554503755',
          orderId: '130169572291521792',
          orderNo: '130169571554503755',
          orderType: 0,
          orderSubType: 0,
          orderStatus: 50,
          orderSubStatus: null,
          totalAmount: '400000',
          goodsAmount: '400000',
          goodsAmountApp: '400000',
          paymentAmount: '400000',
          freightFee: '0',
          packageFee: '0',
          discountAmount: '0',
          channelType: 0,
          channelSource: '',
          channelIdentity: '',
          remark: '',
          cancelType: null,
          cancelReasonType: null,
          cancelReason: null,
          rightsType: null,
          createTime: '1587008200590',
          orderItemVOs: [
            {
              id: '130169572425740032',
              orderNo: null,
              spuId: '1',
              skuId: '135691631',
              roomId: null,
              goodsMainType: 0,
              goodsViceType: 0,
              goodsName:
                '養殖サバ',
              goodsPictureUrl: 'cloud://nagashiro-7gx3ygvt2a49505e.6e61-nagashiro-7gx3ygvt2a49505e-1327079852/images/goods_demo_rename/A/A1/01.jpg',
              originPrice: '20000',
              actualPrice: '20000',
              specifications: [
              ],
              buyQuantity: 20,
              itemTotalAmount: '400000',
              itemDiscountAmount: '0',
              itemPaymentAmount: '400000',
              goodsPaymentPrice: '400000',
              tagPrice: null,
              tagText: null,
              outCode: null,
              labelVOs: null,
              buttonVOs: [
                {
                  primary: true,
                  type: 4,
                  name: '',
                },
              ],
            },
          ],
          logisticsVO: {
            logisticsType: 1,
            logisticsNo: '123',
            logisticsStatus: null,
            logisticsCompanyCode: 'zhongtong',
            logisticsCompanyName: '中通速递',
            receiverAddressId: '2',
            provinceCode: '440000',
            cityCode: '440300',
            countryCode: '440306',
            receiverProvince: '广东省',
            receiverCity: '深圳市',
            receiverCountry: '南山区',
            receiverArea: '',
            receiverAddress: '前海路333号阳光玫瑰园',
            receiverPostCode: '',
            receiverLongitude: '113.829127',
            receiverLatitude: '22.713649',
            receiverIdentity: '88888888205468',
            receiverPhone: '17612345678',
            receiverName: '平均线',
            expectArrivalTime: null,
            senderName: '',
            senderPhone: '',
            senderAddress: '',
            sendTime: '1587008529453',
            arrivalTime: '1587008623995',
          },
          paymentVO: {
            payStatus: 1,
            amount: '508200',
            currency: null,
            payType: null,
            payWay: null,
            payWayName: null,
            interactId: null,
            traceNo: null,
            channelTrxNo: null,
            period: null,
            payTime: null,
            paySuccessTime: null,
          },
          buttonVOs: [
            { primary: false, type: 4, name: '申请售后' },
            { primary: true, type: 6, name: '评价' },
          ],
          labelVOs: null,
          invoiceVO: {
            buyerName: '腾讯计算机有限公司', //个人或公司名称
            buyerTaxNo: '9144 9808 0909 0293 XG', //税号
            buyerPhone: '18600008888', //手机
            email: '73900484@qq.com', //邮箱
            titleType: 2, //发票抬头 1-个人 2-公司
            ontentType: 1, //发票内容 1-明细 2类别
            invoiceType: 5, //是否开票 0-不开 5-电子发票
            money: '1.54',
          },
          couponAmount: null,
          autoCancelTime: null,
          orderStatusName: '交易完成',
          orderSatusRemark: null,
          logisticsLogVO: null,
          invoiceStatus: null,
          invoiceDesc: null,
          invoiceUrl: null,
        },
        {
          saasId: '88888888',
          storeId: '1000',
          storeName: 'NAGASHIRO水产东京旗舰店',
          uid: '88888888205468',
          parentOrderNo: '130150835531421259',
          orderId: '130150836385879808',
          orderNo: '130150835531421259',
          orderType: 0,
          orderSubType: 0,
          orderStatus: 50,
          orderSubStatus: null,
          totalAmount: '38000',
          goodsAmount: '38000',
          goodsAmountApp: '38000',
          paymentAmount: '38000',
          freightFee: '0',
          packageFee: '0',
          discountAmount: '0',
          channelType: 0,
          channelSource: '',
          channelIdentity: '',
          remark: '',
          cancelType: null,
          cancelReasonType: null,
          cancelReason: null,
          rightsType: null,
          createTime: '1587007083842',
          orderItemVOs: [
            {
              id: '130150836520098048',
              orderNo: null,
              spuId: '15',
              skuId: '135681631',
              roomId: null,
              goodsMainType: 0,
              goodsViceType: 0,
              goodsName:
                '鱈白子',
              goodsPictureUrl: 'cloud://nagashiro-7gx3ygvt2a49505e.6e61-nagashiro-7gx3ygvt2a49505e-1327079852/images/goods_demo_rename/A/A8/01.jpg',
              originPrice: '38000',
              actualPrice: '38000',
              specifications: [
              ],
              buyQuantity: 1,
              itemTotalAmount: '38000',
              itemDiscountAmount: '0',
              itemPaymentAmount: '38000',
              goodsPaymentPrice: '38000',
              tagPrice: null,
              tagText: null,
              outCode: null,
              labelVOs: null,
              buttonVOs: null,
            },
          ],
          logisticsVO: {
            logisticsType: 1,
            logisticsNo: '123',
            logisticsStatus: null,
            logisticsCompanyCode: 'yuantong',
            logisticsCompanyName: '圆通速递',
            receiverAddressId: '2',
            provinceCode: '440000',
            cityCode: '440300',
            countryCode: '440306',
            receiverProvince: '广东省',
            receiverCity: '深圳市',
            receiverCountry: '南山区',
            receiverArea: '',
            receiverAddress: '前海路333号阳光玫瑰园',
            receiverPostCode: '',
            receiverLongitude: '113.829127',
            receiverLatitude: '22.713649',
            receiverIdentity: '88888888205468',
            receiverPhone: '17612345678',
            receiverName: '平均线',
            expectArrivalTime: null,
            senderName: '',
            senderPhone: '',
            senderAddress: '',
            sendTime: '1587008539953',
            arrivalTime: '1588291200508',
          },
          paymentVO: {
            payStatus: 1,
            amount: '4000',
            currency: null,
            payType: null,
            payWay: null,
            payWayName: null,
            interactId: null,
            traceNo: null,
            channelTrxNo: null,
            period: null,
            payTime: null,
            paySuccessTime: null,
          },
          buttonVOs: [{ primary: true, type: 6, name: '评价' }],
          labelVOs: null,
          invoiceVO: null,
          couponAmount: null,
          autoCancelTime: null,
          orderStatusName: '交易完成',
          orderSatusRemark: null,
          logisticsLogVO: null,
          invoiceStatus: null,
          invoiceDesc: null,
          invoiceUrl: null,
        },
      ],
    },
    code: 'Success',
    msg: null,
    requestId: mockReqId(),
    clientIp: mockIp(),
    rt: 113,
    success: true,
  };
  const { pageNum, pageSize, orderStatus } = params.parameter;
  // 实现筛选
  if (orderStatus > -1) {
    resp.data.orders = resp.data.orders.filter(
      (order) => order.orderStatus === orderStatus,
    );
  }
  // 实现分页
  resp.data.pageNum = pageNum;
  resp.data.pageSize = pageSize;
  resp.data.orders = resp.data.orders.slice(
    (pageNum - 1) * pageSize,
    pageNum * pageSize,
  );
  return resp;
}

export function genOrdersCount() {
  const resp = {
    data: [
      { tabType: 5, orderNum: 1 },
      { tabType: 10, orderNum: 1 },
      { tabType: 40, orderNum: 1 },
      { tabType: 50, orderNum: 2 },
    ],
    code: 'Success',
    msg: null,
    requestId: mockReqId(),
    clientIp: mockIp(),
    rt: 41,
    success: true,
  };
  return resp;
}
